"""
Backup Server
protocol.py: contains protocol information
"""

from enum import IntEnum


# Sizes
class Size(IntEnum):
    UUID = 16
    VERSION = 1
    REQ_RES_CODE = 2
    PAYLOAD_SIZE = 4
    USER_NAME = 255
    FILE_NAME = 255
    PUBLIC_KEY = 160
    AES_KEY = 16
    ENCRYPTED_AES_KEY = 8 * AES_KEY
    FILE_SIZE = 4
    REQ_HEADER = UUID + VERSION + REQ_RES_CODE + PAYLOAD_SIZE
    RES_HEADER = VERSION + REQ_RES_CODE + PAYLOAD_SIZE


# Request
class ReqCode(IntEnum):
    REGISTER = 1100
    PUBLIC_KEY = 1101
    LOGIN = 1102
    BACKUP_FILE = 1103
    CRC_VALID = 1104
    CRC_INVALID_RETRYING = 1105
    CRC_INVALID_ABORTING = 1106


REQ_HEADER = f'<{Size.UUID}scHL'
REQ_USER_NAME_PAYLOAD = f'{Size.USER_NAME}s'
REQ_FILE_NAME_PAYLOAD = f'{Size.FILE_NAME}s'
REQ_PUBLIC_KEY_PAYLOAD = f'{Size.USER_NAME}s{Size.PUBLIC_KEY}s'
REQ_FILE_PAYLOAD = f'<L{Size.FILE_NAME}s'


# Response
class ResCode(IntEnum):
    REGISTER_SUCCESS = 2100
    REGISTER_FAILURE = 2101
    PUBLIC_KEY_RECEIVED_SENDING_AES_KEY = 2102
    FILE_RECEIVED_SENDING_CRC = 2103
    ACKNOWLEDGE = 2104
    LOGIN_SUCCESS_SENDING_AES_KEY = 2105
    LOGIN_FAILURE = 2106
    GENERAL_FAILURE = 2107


RES_HEADER = '<cHL'
RES_UUID_PAYLOAD = f'{Size.UUID}s'
RES_ENCRYPTED_AES_PAYLOAD = RES_UUID_PAYLOAD + f'{Size.ENCRYPTED_AES_KEY}s'
RES_CRC_PAYLOAD = f'<L{Size.FILE_NAME}sL'

