"""
Backup Server
protocol.py: contains protocol information
"""

from enum import IntEnum


# Sizes
class Size(IntEnum):
    VERSION = 1
    REQ_RES_CODE = 2
    CRC = 4
    PAYLOAD_SIZE = 4
    CONTENT_SIZE = 4
    CLIENT_ID = 16
    AES_KEY = 16
    ENCRYPTED_AES_KEY = 8 * AES_KEY
    PUBLIC_KEY = 160
    CLIENT_NAME = 255
    FILE_NAME = 255


# Request
class ReqCode(IntEnum):
    REGISTER = 1100
    KEY_EXCHANGE = 1101
    LOGIN = 1102
    BACKUP_FILE = 1103
    CRC_VALID = 1104
    CRC_INVALID_RETRYING = 1105
    CRC_INVALID_ABORTING = 1106


REQ_HEADER = f'<{Size.CLIENT_ID}scHL'
REQ_CLIENT_NAME_PAYLOAD = f'{Size.CLIENT_NAME}s'
REQ_FILE_NAME_PAYLOAD = f'{Size.FILE_NAME}s'
REQ_PUBLIC_KEY_PAYLOAD = f'{Size.CLIENT_NAME}s{Size.PUBLIC_KEY}s'
REQ_FILE_PAYLOAD = f'<L{Size.FILE_NAME}s'


REQUEST_SIZES = {REQ_HEADER: (Size.CLIENT_ID + Size.VERSION + Size.REQ_RES_CODE + Size.PAYLOAD_SIZE),
                 REQ_CLIENT_NAME_PAYLOAD: Size.CLIENT_NAME,
                 REQ_FILE_NAME_PAYLOAD: Size.FILE_NAME,
                 REQ_PUBLIC_KEY_PAYLOAD: Size.CLIENT_NAME + Size.PUBLIC_KEY,
                 REQ_FILE_PAYLOAD: Size.CONTENT_SIZE + Size.FILE_NAME}


# Response
class ResCode(IntEnum):
    REGISTER_SUCCESS = 2100
    REGISTER_FAILURE = 2101
    PUBLIC_KEY_RECEIVED = 2102
    FILE_RECEIVED = 2103
    ACKNOWLEDGE = 2104
    LOGIN_SUCCESS = 2105
    LOGIN_FAILURE = 2106
    GENERAL_FAILURE = 2107


RES_HEADER = '<cHL'
RES_CLIENT_ID_PAYLOAD = f'{Size.CLIENT_ID}s'
RES_ENCRYPTED_AES_PAYLOAD = f'{Size.CLIENT_ID}s{Size.ENCRYPTED_AES_KEY}s'
RES_CRC_PAYLOAD = f'{Size.CLIENT_ID}sL{Size.FILE_NAME}sL'


RESPONSE_SIZES = {RES_HEADER: (Size.VERSION + Size.REQ_RES_CODE + Size.PAYLOAD_SIZE),
                  RES_CLIENT_ID_PAYLOAD: Size.CLIENT_ID,
                  RES_ENCRYPTED_AES_PAYLOAD: (Size.CLIENT_ID + Size.ENCRYPTED_AES_KEY),
                  RES_CRC_PAYLOAD: (Size.CLIENT_ID + Size.CONTENT_SIZE + Size.FILE_NAME + Size.CRC)}
